### ISSUE TITLE
How can i get the the "contentDetails" and "statistics" objects through youtube.search() method

### ISSUE THREAD

**Issue by muhammadzafarnaeem** [paulomcnally/youtube-node#14]
youTube.getById() gives "contentDetails" and "statistics" objects but I want to get  "contentDetails" and "statistics" objects and "publishedby" element through youtube.search() method.I have add the following code in self.search() method in youtube.js.        
```javascript
   self.search = function(query, maxResults, callback) {
   var validate = self.validate();
   if (validate !== null) {
      callback(validate);
    }
    else {
      self.clearParts();
      self.addPart('snippet');
      self.addPart('contentDetails');
      self.addPart('status');
      self.addParam('part', self.getParts());
      self.addParam('q', query);
      self.addParam('maxResults', maxResults);
    self.request(self.getUrl('search'), callback);
    }
  };   
```
But it gives the following error.
```javascript
{ errors: 
   [ { domain: 'youtube.part',
       reason: 'unknownPart',
       message: 'contentDetails',
       locationType: 'parameter',
       location: 'part' },
     { domain: 'youtube.part',
       reason: 'unknownPart',
       message: 'status',
       locationType: 'parameter',
       location: 'part' } ],
  code: 400,
  message: 'contentDetails' }
```
Is it possible to get  "contentDetails" and "statistics" objects and "publishedby" element through youtube.search() method? if possible then how can i get this?

**Comment by paulomcnally** [comment]
Check validez params here https://developers.google.com/youtube/v3/docs/search

**Comment by paulomcnally** [comment]
https://developers.google.com/youtube/v3/docs/search/list

ContentDetail is not allowes.

Sorry
